-- ==============================================================================
-- PERSONALGYM - SCRIPT DE MULTI-TENANCY E SEGURANÇA AVANÇADA (SUPABASE)
-- ==============================================================================
-- Este script configura isolamento absoluto de dados entre múltiplos Personal Trainers.
-- Cada profissional cadastrado no sistema terá acesso EXCLUSIVO aos seus próprios alunos,
-- agendamentos, cargas, históricos e fotos. Nenhum profissional enxerga dados de outro.

-- ------------------------------------------------------------------------------
-- 1. CRIAÇÃO DAS TABELAS (SE AINDA NÃO EXISTIREM)
-- ------------------------------------------------------------------------------

-- Tabela de Alunos
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    plan TEXT,
    weight NUMERIC DEFAULT 0,
    body_fat NUMERIC DEFAULT 0,
    active BOOLEAN DEFAULT true,
    frequency NUMERIC DEFAULT 0,
    avatar TEXT,
    photo_before TEXT,
    photo_after TEXT,
    monthly_fee NUMERIC DEFAULT 0,
    due_date INTEGER DEFAULT 10,
    last_payment_date TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Eventos da Agenda
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    type TEXT DEFAULT 'class',
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Evolução de Cargas
CREATE TABLE IF NOT EXISTS public.load_progression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    exercise TEXT NOT NULL,
    load NUMERIC DEFAULT 0,
    week TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Histórico Emocional Pós-Treino
CREATE TABLE IF NOT EXISTS public.emotional_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    score NUMERIC DEFAULT 0,
    record_date TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Metas Financeiras (1 registro por profissional)
CREATE TABLE IF NOT EXISTS public.financial_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monthly_goal NUMERIC DEFAULT 0,
    quarterly_goal NUMERIC DEFAULT 0,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid() UNIQUE,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------------------------
-- 2. GARANTIR COLUNAS E RESTRIÇÕES EM TABELAS EXISTENTES
-- ------------------------------------------------------------------------------
DO $$ 
BEGIN
    -- students: coluna user_id
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='students' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='user_id') THEN
            ALTER TABLE public.students ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='monthly_fee') THEN
            ALTER TABLE public.students ADD COLUMN monthly_fee NUMERIC DEFAULT 0;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='due_date') THEN
            ALTER TABLE public.students ADD COLUMN due_date INTEGER DEFAULT 10;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='last_payment_date') THEN
            ALTER TABLE public.students ADD COLUMN last_payment_date TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='photo_before') THEN
            ALTER TABLE public.students ADD COLUMN photo_before TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='photo_after') THEN
            ALTER TABLE public.students ADD COLUMN photo_after TEXT;
        END IF;
    END IF;

    -- calendar_events: user_id
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='calendar_events' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='calendar_events' AND column_name='user_id') THEN
            ALTER TABLE public.calendar_events ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;

    -- load_progression: user_id
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='load_progression' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='load_progression' AND column_name='user_id') THEN
            ALTER TABLE public.load_progression ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;

    -- emotional_history: user_id e record_date
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='emotional_history' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='emotional_history' AND column_name='user_id') THEN
            ALTER TABLE public.emotional_history ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='emotional_history' AND column_name='record_date') THEN
            ALTER TABLE public.emotional_history ADD COLUMN record_date TEXT;
        END IF;
    END IF;

    -- financial_goals: user_id e constraint unique
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='financial_goals' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='financial_goals' AND column_name='user_id') THEN
            ALTER TABLE public.financial_goals ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 3. HABILITAR ROW LEVEL SECURITY (RLS) RIGOROSO
-- ------------------------------------------------------------------------------
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.load_progression ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emotional_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_goals ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- 4. POLÍTICAS DE SEGURANÇA MULTI-TENANT (ISOLAMENTO POR PROFISSIONAL)
-- Cada personal trainer só consegue visualizar, inserir, editar e excluir seus PRÓPRIOS dados.
-- ------------------------------------------------------------------------------

-- Tabela: students
DROP POLICY IF EXISTS "Acesso restrito a autenticados em students" ON public.students;
DROP POLICY IF EXISTS "MultiTenant: Acesso aos proprios alunos" ON public.students;
CREATE POLICY "MultiTenant: Acesso aos proprios alunos"
ON public.students FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Tabela: calendar_events
DROP POLICY IF EXISTS "Acesso restrito a autenticados em calendar_events" ON public.calendar_events;
DROP POLICY IF EXISTS "MultiTenant: Acesso aos proprios eventos" ON public.calendar_events;
CREATE POLICY "MultiTenant: Acesso aos proprios eventos"
ON public.calendar_events FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (
    auth.uid() = user_id AND 
    (student_id IS NULL OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.user_id = auth.uid()))
);

-- Tabela: load_progression
DROP POLICY IF EXISTS "Acesso restrito a autenticados em load_progression" ON public.load_progression;
DROP POLICY IF EXISTS "MultiTenant: Acesso as proprias cargas" ON public.load_progression;
CREATE POLICY "MultiTenant: Acesso as proprias cargas"
ON public.load_progression FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (
    auth.uid() = user_id AND 
    (student_id IS NULL OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.user_id = auth.uid()))
);

-- Tabela: emotional_history
DROP POLICY IF EXISTS "Acesso restrito a autenticados em emotional_history" ON public.emotional_history;
DROP POLICY IF EXISTS "MultiTenant: Acesso aos proprios humores" ON public.emotional_history;
CREATE POLICY "MultiTenant: Acesso aos proprios humores"
ON public.emotional_history FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (
    auth.uid() = user_id AND 
    (student_id IS NULL OR EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_id AND s.user_id = auth.uid()))
);

-- Tabela: financial_goals
DROP POLICY IF EXISTS "Acesso restrito a autenticados em financial_goals" ON public.financial_goals;
DROP POLICY IF EXISTS "MultiTenant: Acesso as proprias metas" ON public.financial_goals;
CREATE POLICY "MultiTenant: Acesso as proprias metas"
ON public.financial_goals FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ------------------------------------------------------------------------------
-- 5. BLINDAGEM DO STORAGE (FOTOS DE AVALIAÇÃO FÍSICA)
-- Bucket privado com isolamento de pasta por UID do profissional
-- ------------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('evaluations', 'evaluations', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- Upload restrito à pasta do próprio usuário (ex: <user_id>/foto.jpg)
DROP POLICY IF EXISTS "Upload autenticado de avaliacoes" ON storage.objects;
DROP POLICY IF EXISTS "MultiTenant: Upload avaliacoes na pasta do usuario" ON storage.objects;
CREATE POLICY "MultiTenant: Upload avaliacoes na pasta do usuario"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
    bucket_id = 'evaluations' AND 
    (storage.foldername(name))[1] = auth.uid()::text
);

-- Leitura restrita à pasta do próprio usuário
DROP POLICY IF EXISTS "Leitura autenticada de avaliacoes" ON storage.objects;
DROP POLICY IF EXISTS "MultiTenant: Leitura avaliacoes da pasta do usuario" ON storage.objects;
CREATE POLICY "MultiTenant: Leitura avaliacoes da pasta do usuario"
ON storage.objects FOR SELECT TO authenticated
USING (
    bucket_id = 'evaluations' AND 
    (storage.foldername(name))[1] = auth.uid()::text
);

-- Exclusão restrita à pasta do próprio usuário
DROP POLICY IF EXISTS "Exclusao autenticada de avaliacoes" ON storage.objects;
DROP POLICY IF EXISTS "MultiTenant: Exclusao avaliacoes da pasta do usuario" ON storage.objects;
CREATE POLICY "MultiTenant: Exclusao avaliacoes da pasta do usuario"
ON storage.objects FOR DELETE TO authenticated
USING (
    bucket_id = 'evaluations' AND 
    (storage.foldername(name))[1] = auth.uid()::text
);
