-- ==============================================================================
-- PERSONALGYM - SCRIPT COMPLETO DE CRIAÇÃO, ESTRUTURA E SEGURANÇA (SUPABASE)
-- ==============================================================================
-- Este script é 100% seguro para rodar no Supabase SQL Editor.
-- Ele cria as tabelas que ainda não existem (como financial_goals),
-- adiciona colunas necessárias e ativa a proteção Row Level Security (RLS).

-- ------------------------------------------------------------------------------
-- 1. CRIAÇÃO DAS TABELAS (SE AINDA NÃO EXISTIREM)
-- ------------------------------------------------------------------------------

-- Tabela de Alunos
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    plan TEXT,
    weight NUMERIC DEFAULT 0,
    body_fat NUMERIC DEFAULT 0,
    active BOOLEAN DEFAULT true,
    frequency NUMERIC DEFAULT 0,
    avatar TEXT,
    photo_before TEXT,
    photo_after TEXT,
    monthly_fee NUMERIC DEFAULT 0,
    due_date INTEGER DEFAULT 10,
    last_payment_date TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Eventos da Agenda
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    type TEXT DEFAULT 'class',
    student_id BIGINT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Evolução de Cargas
CREATE TABLE IF NOT EXISTS public.load_progression (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    exercise TEXT NOT NULL,
    load NUMERIC DEFAULT 0,
    week TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Histórico Emocional Pós-Treino
CREATE TABLE IF NOT EXISTS public.emotional_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    score NUMERIC DEFAULT 0,
    date TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabela de Metas Financeiras
CREATE TABLE IF NOT EXISTS public.financial_goals (
    id BIGINT PRIMARY KEY DEFAULT 1,
    monthly_goal NUMERIC DEFAULT 0,
    quarterly_goal NUMERIC DEFAULT 0,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Inicializar linha padrão de metas (ID 1) caso não exista
INSERT INTO public.financial_goals (id, monthly_goal, quarterly_goal)
VALUES (1, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- 2. GARANTIR COLUNAS EM TABELAS PRÉ-EXISTENTES
-- ------------------------------------------------------------------------------
DO $$ 
BEGIN
    -- students
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='students' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='user_id') THEN
            ALTER TABLE public.students ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='monthly_fee') THEN
            ALTER TABLE public.students ADD COLUMN monthly_fee NUMERIC DEFAULT 0;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='due_date') THEN
            ALTER TABLE public.students ADD COLUMN due_date INTEGER DEFAULT 10;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='last_payment_date') THEN
            ALTER TABLE public.students ADD COLUMN last_payment_date TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='photo_before') THEN
            ALTER TABLE public.students ADD COLUMN photo_before TEXT;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='photo_after') THEN
            ALTER TABLE public.students ADD COLUMN photo_after TEXT;
        END IF;
    END IF;

    -- calendar_events
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='calendar_events' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='calendar_events' AND column_name='user_id') THEN
            ALTER TABLE public.calendar_events ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;

    -- load_progression
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='load_progression' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='load_progression' AND column_name='user_id') THEN
            ALTER TABLE public.load_progression ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;

    -- emotional_history
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='emotional_history' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='emotional_history' AND column_name='user_id') THEN
            ALTER TABLE public.emotional_history ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;

    -- financial_goals
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='financial_goals' AND table_schema='public') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='financial_goals' AND column_name='user_id') THEN
            ALTER TABLE public.financial_goals ADD COLUMN user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
        END IF;
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 3. HABILITAR ROW LEVEL SECURITY (RLS)
-- ------------------------------------------------------------------------------
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.load_progression ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emotional_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_goals ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- 4. POLÍTICAS DE SEGURANÇA (APENAS USUÁRIOS AUTENTICADOS)
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Acesso restrito a autenticados em students" ON public.students;
CREATE POLICY "Acesso restrito a autenticados em students"
ON public.students FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Acesso restrito a autenticados em calendar_events" ON public.calendar_events;
CREATE POLICY "Acesso restrito a autenticados em calendar_events"
ON public.calendar_events FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Acesso restrito a autenticados em load_progression" ON public.load_progression;
CREATE POLICY "Acesso restrito a autenticados em load_progression"
ON public.load_progression FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Acesso restrito a autenticados em emotional_history" ON public.emotional_history;
CREATE POLICY "Acesso restrito a autenticados em emotional_history"
ON public.emotional_history FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Acesso restrito a autenticados em financial_goals" ON public.financial_goals;
CREATE POLICY "Acesso restrito a autenticados em financial_goals"
ON public.financial_goals FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

-- ------------------------------------------------------------------------------
-- 5. BLINDAGEM DO STORAGE (FOTOS DE AVALIAÇÃO FÍSICA)
-- ------------------------------------------------------------------------------
-- Cria o bucket 'evaluations' como privado caso ainda não exista
INSERT INTO storage.buckets (id, name, public)
VALUES ('evaluations', 'evaluations', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- Políticas de Storage para o Bucket 'evaluations'
DROP POLICY IF EXISTS "Upload autenticado de avaliacoes" ON storage.objects;
CREATE POLICY "Upload autenticado de avaliacoes"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'evaluations');

DROP POLICY IF EXISTS "Leitura autenticada de avaliacoes" ON storage.objects;
CREATE POLICY "Leitura autenticada de avaliacoes"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'evaluations');

DROP POLICY IF EXISTS "Exclusao autenticada de avaliacoes" ON storage.objects;
CREATE POLICY "Exclusao autenticada de avaliacoes"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'evaluations');
